### ISSUE TITLE
compile error with Arduino Mega

### ISSUE THREAD

**Issue by torinnguyen** [Seeed-Studio/Suli#1]
suli_uart_write_float
suli_uart_write_int
These 2 functions should not return value (void function) in case of **AVR_ATmega1280** or **AVR_ATmega2560**

**Comment by victoryforphil** [comment]
YES!

**Comment by gvgosnell** [comment]
go into the suli.cpp file and remove the return values from the error uart functions.
it then compiles.

**Comment by awong1900** [comment]
OK。You are right.   thx @gvgosnell @AtecStudios  @torinnguyen

**Comment by serch2015** [comment]
i got the following errors, when i try to compile the library, using an mega2560 and a seeed gprs v2 shield
i am new using suli, somebody could help me

C:\Users\yop\Documents\Arduino\libraries\Suli_Arduino\Suli.cpp: In function 'void suli_uart_write_int(void*, int16, int32)':
C:\Users\yop\Documents\Arduino\libraries\Suli_Arduino\Suli.cpp:434:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return Serial1.print(num);
                                 ^
C:\Users\yop\Documents\Arduino\libraries\Suli_Arduino\Suli.cpp:438:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return Serial2.print(num);
                                 ^
C:\Users\yop\Documents\Arduino\libraries\Suli_Arduino\Suli.cpp:442:33: error: return-statement with a value, in function returning 'void' [-fpermissive]
         return Serial3.print(num);
                                 ^
Error compiling.
