### ISSUE TITLE
Compile Error for Mbed

### ISSUE THREAD

**Issue by FriedCircuits** [Seeed-Studio/Suli#2]
Trying to compile for Arch Pro

Errors on 
Error: Argument of type "PinDirection" is incompatible with parameter of type "PinName" in "Suli/Suli.cpp", Line: 15, Col: 20
 Any ideas?

**Comment by FriedCircuits** [comment]
I changed it to pin instead of PIN_INPUT but still didn't work. But at least Suli compiled. I got the display working 96x96 without using Suli. Someone ported the Arduino direct method to mbed.

**Comment by awong1900** [comment]
Thx @FriedCircuits .  Fixed it.
