### ISSUE TITLE
MCU mode

### ISSUE THREAD

**Issue by mostafa-elboss** [Seeed-Studio/Suli#4]
iam trying to send and receive data with meshbee MCU mode 
but it always fail  
could any one put a simple example for me 
thanks

**Comment by KillingJacky** [comment]
Hi mostafa,

Please find the cook book and user manual at the google group of mesh bee. 
https://groups.google.com/forum/#!topic/seeedstudio-mesh-bee-discussion-group/NByFzvWBsWg

**Comment by mostafa-elboss** [comment]
i turns out that i was using old version of cookbook 
i tried the API in the new version but there is no aupsairportreadable function or aups air port read 

is there new version of the firmware or i have missing files ?
